/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GameTypeTabbar: typeof import('./src/components/tabbar/GameTypeTabbar.vue')['default']
    HeaderBack: typeof import('./src/components/headerBack/HeaderBack.vue')['default']
    MainBottomTab: typeof import('./src/components/tabbar/MainBottomTab.vue')['default']
    PokerTableCard: typeof import('./src/components/listItem/PokerTableCard.vue')['default']
    PokerTableGroupCard: typeof import('./src/components/listItem/PokerTableGroupCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopActionButton: typeof import('./src/components/button/TopActionButton.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
