#!/usr/bin/env python3
import glob
import json
import os
import re
import shutil
import sys
import tempfile
from multiprocessing import Pool

try:
    from fontTools import subset
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit('[fonts:split] fonttools is required: pip install fonttools brotli')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'scripts/fonts/HONORSansCN-Regular.woff2')
OUT_DIR = os.path.join(ROOT, 'src/assets/fonts/honor-sans-cn')
SCSS = os.path.join(ROOT, 'src/styles/_fonts-honor.scss')
LOCALES_DIR = os.path.join(ROOT, 'public/i18n')
FAMILY = 'HONOR Sans CN'
FILE_PREFIX = 'honor-sans-cn'
EXT_SLICE_SIZE = 400


def is_han(cp):
    return 0x3400 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF or 0x20000 <= cp <= 0x3FFFF


def read_source():
    chunks = []
    for pattern in ('src/**/*.vue', 'src/**/*.ts', 'src/**/*.scss', 'index.html'):
        for path in glob.glob(os.path.join(ROOT, pattern), recursive=True):
            with open(path, encoding='utf-8', errors='ignore') as handle:
                chunks.append(handle.read())
    return '\n'.join(chunks)


def read_locale(locale):
    files = glob.glob(os.path.join(LOCALES_DIR, 'h5-cc-i18n.%s.*.js' % locale))
    if not files:
        sys.exit('[fonts:split] missing %s dictionary in public/i18n, run pnpm sync:i18n first' % locale)
    with open(files[0], encoding='utf-8') as handle:
        code = handle.read()
    return json.loads(code[code.index('m=') + 2:code.rindex(';if(r&&r.registerLocale)')])


def strip_comments(text):
    text = re.sub(r'/\*.*?\*/|<!--.*?-->', '', text, flags=re.S)
    return re.sub(r'//[^\n]*', '', text)


def han_of(texts):
    return [ord(ch) for text in texts for ch in text if is_han(ord(ch))]


def plan_slices(cmap):
    remaining = set(cmap)
    slices = []

    def take(name, codepoints):
        picked = sorted({cp for cp in codepoints if cp in remaining})
        if picked:
            remaining.difference_update(picked)
            slices.append((name, picked))

    take('latin', [cp for cp in cmap if cp <= 0x052F or 0x2000 <= cp <= 0x206F or 0x20A0 <= cp <= 0x20CF])
    take('symbols', [cp for cp in cmap if cp < 0x2E80])
    take('cjk-common', [cp for cp in cmap if 0x3000 <= cp <= 0x303F or 0xFE10 <= cp <= 0xFE6F or 0xFF00 <= cp <= 0xFFEF])

    source = read_source()
    literals = set(re.findall(r"""['"`]([A-Za-z0-9_.\-]+)['"`]""", source))
    zh_cn = read_locale('zh-CN')
    zh_tw = read_locale('zh-TW')
    ja = read_locale('ja')

    take('sc-1', han_of(value for key, value in zh_cn.items() if key in literals) + han_of([strip_comments(source)]))
    take('sc-2', han_of(zh_cn.values()) + han_of([source]))
    take('tc-1', han_of(value for key, value in zh_tw.items() if key in literals))
    take('tc-2', han_of(zh_tw.values()))
    take('ja', [cp for cp in cmap if 0x3040 <= cp <= 0x30FF or 0x31F0 <= cp <= 0x31FF] + han_of(ja.values()))

    rest = sorted(remaining)
    for index in range(0, len(rest), EXT_SLICE_SIZE):
        slices.append(('ext-%02d' % (index // EXT_SLICE_SIZE + 1), rest[index:index + EXT_SLICE_SIZE]))
    return slices


def build_slice(job):
    ttf_path, name, codepoints = job
    options = subset.Options()
    options.flavor = 'woff2'
    options.layout_features = ['*']
    options.notdef_outline = True
    options.name_IDs = [1, 2, 3, 4, 6]
    font = subset.load_font(ttf_path, options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    file_name = '%s-%s.woff2' % (FILE_PREFIX, name)
    out_path = os.path.join(OUT_DIR, file_name)
    subset.save_font(font, out_path, options)
    return name, file_name, os.path.getsize(out_path)


def unicode_range(codepoints):
    parts = []
    start = prev = codepoints[0]
    for cp in codepoints[1:] + [None]:
        if cp is not None and cp == prev + 1:
            prev = cp
            continue
        parts.append('U+%X' % start if start == prev else 'U+%X-%X' % (start, prev))
        start = prev = cp
    return ', '.join(parts)


def render_scss(slices, file_names):
    lines = ['// AUTO-GENERATED by scripts/split-font.py. DO NOT EDIT.', '']
    for name, codepoints in slices:
        lines += [
            '@font-face {',
            "  font-family: '%s';" % FAMILY,
            "  src: url('@/assets/fonts/honor-sans-cn/%s') format('woff2');" % file_names[name],
            '  font-weight: 400;',
            '  font-style: normal;',
            '  font-display: swap;',
            '  unicode-range: %s;' % unicode_range(codepoints),
            '}',
            '',
        ]
    return '\n'.join(lines)


def main():
    if not os.path.exists(SOURCE):
        sys.exit('[fonts:split] missing source font: %s' % SOURCE)

    source_font = TTFont(SOURCE, recalcTimestamp=False)
    cmap = set(source_font.getBestCmap())
    slices = plan_slices(cmap)

    covered = set()
    for _, codepoints in slices:
        covered.update(codepoints)
    if covered != cmap or sum(len(c) for _, c in slices) != len(cmap):
        sys.exit('[fonts:split] slices do not cover the font exactly')

    work_dir = tempfile.mkdtemp(prefix='split-font-')
    try:
        ttf_path = os.path.join(work_dir, 'source.ttf')
        source_font.flavor = None
        source_font.save(ttf_path)

        shutil.rmtree(OUT_DIR, ignore_errors=True)
        os.makedirs(OUT_DIR)
        with Pool() as pool:
            results = pool.map(build_slice, [(ttf_path, name, codepoints) for name, codepoints in slices])
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)

    file_names = {}
    total = 0
    for (name, codepoints), (_, file_name, size) in zip(slices, results):
        file_names[name] = file_name
        total += size
        print('[fonts:split] %-16s %6d chars %8d bytes' % (name, len(codepoints), size))

    with open(SCSS, 'w', encoding='utf-8') as handle:
        handle.write(render_scss(slices, file_names))
    print('[fonts:split] %d slices, %d bytes total -> %s' % (len(slices), total, os.path.relpath(OUT_DIR, ROOT)))


if __name__ == '__main__':
    main()
